### PR TITLE
support for newer zola(0.11.0)

### PR DESCRIPTION
**Pull request by LarryHsiao**
rename 'generate_rss' to 'generate_feed'

### CODE REVIEW

**Comment by LarryHsiao** [comment]
Close this pull request,
the Netlify check's with zola 0.9.0

**Comment by insipx** [comment]
I've changed the zola version to 0.11.0 in the netlify backend

If you could change the installation steps to be from `0.11.0 +` in the Readme instead of 0.4, and then commit this to see if it passes the checks I can merge this PR.

**Comment by therealprof** [comment]
Any chance to get this merged so I can upgrade my blog? ;)

**Comment by insipx** [comment]
> Any chance to get this merged so I can upgrade my blog? ;)

sorry, was busy and forgot about this! Thanks for the PR, just merged :)

**Pull request merged**
