### PR TITLE
Add social link support for Reddit and Keybase

### LINKED ISSUE #9: Social: Keybase
Keybase is missing from the social list.

### LINKED ISSUE #11: Social: Reddit
It would be nice to see [Reddit](https://www.reddit.com) as a social network option. Profile URLs are in this format:
```
https://www.reddit.com/u/${PROFILE}/
```

### PR DESCRIPTION
**Pull request by ebkalderon**
### Added

* Add social media macro for Keybase.
* Add social media macro for Reddit.

### Changed

* Mention LinkedIn support in `README.md`.

Closes #9.
Closes #11.

### CODE REVIEW

**Review by insipx — CHANGES_REQUESTED** [review]
looks good!

You missed adding the social icons to the sidebar as well, though, https://github.com/insipx/Ergo/blob/73e4407516ee046657e5b2bc0bd7f9c4b4ef5449/templates/macros.html#L63

**Comment by ebkalderon** [comment]
@insipx Yep, thanks for the prompt review! I also got the Keybase URL incorrect as well, so I fixed that  too. Does the chosen ordering of the social media accounts on the page look good to you?

**Review by insipx — APPROVED** [review]
looks good!

> @insipx Yep, thanks for the prompt review! I also got the Keybase URL incorrect as well, so I fixed that too. Does the chosen ordering of the social media accounts on the page look good to you?

the ordering is fine :+1:

**Comment by ebkalderon** [comment]
Sweet! Thanks for taking a look. Feel free to merge at your leisure, as I don't have permission to do so.

**Pull request merged**
